"""pandaren/observability/backend/markdown.py — Markdown 文件可观测后端

为 AuditLog / Tracer / Metrics / Logger 提供 Markdown 文件持久化后端。
零外部依赖，方便人类直接打开 .md 文件查看和调试。

存储结构（数据隔离改造后）：
  {base_dir}/
  ├── sessions/{session_id}/           ← 按 session 分片，per-file 锁不互相阻塞
  │   ├── audit.md                     ← 该 session 的审计
  │   ├── logs.md                      ← 该 session 的日志
  │   └── traces.md                    ← 该 session 的链路 span
  ├── _no_session/                     ← 无 session 归属的事件（audit/logs/traces 的兜底分片）
  │   ├── audit.md
  │   ├── logs.md
  │   └── traces.md
  └── metrics.md                       ← 不分片（聚合快照，天然全局）

设计取舍（分片 vs 全局，判据：一条记录是「事件流」还是「聚合快照」）：
  - Audit / Logger / Tracer 都是"事件流"（一条记录 = 某个发生在特定 run 里的事件）
    → 按 session 分片，per-file 锁避免高频写串行。span 携带 session_id
      （由 hooks_adapter 从 run 的 session 透传），无归属者落 _no_session。
  - Metrics 是"聚合快照"（对海量事件塌缩后的汇总，覆盖写）→ 不分片，全局单文件。
    若需按会话归因，应在指标数据里加 session 维度标签，而非物理劈分文件。
"""

from __future__ import annotations

import atexit
import logging
import threading
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..types import AuditRecord, Span, SpanType

logger = logging.getLogger("pandaren.observability.backend.markdown")


def _sanitize_component(value: str) -> str:
    """路径分量清洗：防止 session_id 里带 / \\ .. 等字符逃出目录。"""
    if not value:
        return ""
    safe = value.replace("/", "_").replace("\\", "_").replace(":", "-")
    safe = "".join(c for c in safe if c.isalnum() or c in "-_.")
    # 拒绝纯点（.. / .）
    if safe in ("", ".", ".."):
        return ""
    return safe

# ── Markdown 视觉标记（不含 ANSI，纯文本 + emoji）──────────────────────────

_AUDIT_SEVERITY_BADGE: dict[str, str] = {
    "info":     "ℹ️ INFO",
    "warn":     "⚠️ WARN",
    "critical": "🔴 CRITICAL",
}

_LOG_LEVEL_BADGE: dict[str, str] = {
    "DEBUG": "🐛 DEBUG",
    "INFO":  "ℹ️ INFO ",
    "WARN":  "⚠️ WARN ",
    "ERROR": "🔴 ERROR",
}

_SPAN_TYPE_ICON: dict[str, str] = {
    SpanType.RUN.value:           "🚀 run",
    SpanType.STEP.value:          "📍 step",
    SpanType.LLM_CALL.value:      "🤖 llm_call",
    SpanType.TOOL_CALL.value:     "🔧 tool_call",
    SpanType.GUARD_CHECK.value:   "🛡️ guard_check",
    SpanType.HITL_CHECK.value:    "👤 hitl_check",
    SpanType.MESSAGE_BUILD.value: "📝 msg_build",
    SpanType.SKILL_INVOKE.value:  "⚡ skill_invoke",
}


class MarkdownAuditBackend:
    """Markdown 审计日志后端：按 session_id 分片写入。

    路径规则：
      - record.session_id 非空 → {base_dir}/sessions/{sid}/audit.md
      - record.session_id 为空 → {base_dir}/_no_session/audit.md
    """

    _HEADER = (
        "# Audit Log\n\n"
        "> Auto-generated by Pandaren Agent SDK.\n\n"
        "| 时间 | 级别 | 事件 | Agent | Session | Run | Step | 详情 |\n"
        "|------|------|------|-------|---------|-----|------|------|\n"
    )

    def __init__(self, base_dir: str | Path) -> None:
        self._base_dir = Path(base_dir)
        self._base_dir.mkdir(parents=True, exist_ok=True)
        # per-file lock：session A 的 audit 写不阻塞 session B 的 audit 写
        self._locks: dict[Path, threading.Lock] = {}
        self._locks_guard = threading.Lock()
        # 内存镜像仅用于 query()；跨 session 保留（历史行为）
        self._records: list[AuditRecord] = []
        # 记忆已初始化过 header 的文件，避免每次写入都做磁盘检查
        self._headered: set[Path] = set()

    def _resolve_path(self, record: AuditRecord) -> Path:
        sid = _sanitize_component(record.session_id)
        if sid:
            path = self._base_dir / "sessions" / sid / "audit.md"
        else:
            path = self._base_dir / "_no_session" / "audit.md"
        return path

    def _get_lock(self, path: Path) -> threading.Lock:
        # 双检查加锁：避免高频写路径抢 _locks_guard
        lock = self._locks.get(path)
        if lock is not None:
            return lock
        with self._locks_guard:
            lock = self._locks.get(path)
            if lock is None:
                lock = threading.Lock()
                self._locks[path] = lock
            return lock

    def _ensure_header(self, path: Path) -> None:
        if path in self._headered:
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(self._HEADER, encoding="utf-8")
        self._headered.add(path)

    def write(self, record: AuditRecord) -> None:
        path = self._resolve_path(record)
        lock = self._get_lock(path)
        with lock:
            self._ensure_header(path)
            # 全局镜像（跨 session 内存查询，保持向后兼容）
            self._records.append(record)
            ts = record.timestamp.strftime("%H:%M:%S")
            severity_badge = _AUDIT_SEVERITY_BADGE.get(
                record.severity.value, record.severity.value.upper()
            )
            event = f"`{record.event_type.value}`"
            agent_id = record.agent_id or ""
            sess_short = f"`{record.session_id[:12]}`" if record.session_id else ""
            run_short = f"`{record.run_id[:8]}`" if record.run_id else ""
            step = str(record.step_n) if record.step_n is not None else ""
            detail = record.detail.replace("|", "\\|").replace("\n", " ")
            line = (
                f"| {ts} | {severity_badge} | {event} | {agent_id} | "
                f"{sess_short} | {run_short} | {step} | {detail} |\n"
            )
            # 防御：清理 surrogate 字符，避免 open(encoding='utf-8') 抛出 UnicodeEncodeError
            line = line.encode("utf-8", errors="surrogateescape").decode("utf-8", errors="replace")
            with open(path, "a", encoding="utf-8") as f:
                f.write(line)

    def flush(self) -> None:
        pass

    def query(self, agent_id=None, event_type=None,
              start_time=None, end_time=None, limit=100) -> list[AuditRecord]:
        # query 走内存镜像，不做文件读——跨 session 全局视图
        with self._locks_guard:
            results = list(self._records)
        if agent_id:
            results = [r for r in results if r.agent_id == agent_id]
        if event_type:
            results = [r for r in results if r.event_type.value == event_type]
        if start_time:
            from datetime import datetime as _dt
            start_dt = _dt.fromisoformat(start_time) if isinstance(start_time, str) else start_time
            results = [r for r in results if r.timestamp >= start_dt]
        if end_time:
            from datetime import datetime as _dt
            end_dt = _dt.fromisoformat(end_time) if isinstance(end_time, str) else end_time
            results = [r for r in results if r.timestamp <= end_dt]
        results.sort(key=lambda r: r.timestamp, reverse=True)
        return results[:limit]

    def __repr__(self) -> str:
        return f"MarkdownAuditBackend(base_dir='{self._base_dir}', mode='sharded')"


class MarkdownTracerBackend:
    """Markdown Tracer 后端：按 span.session_id 分片追加写入 traces.md。

    路径规则（与 Audit/Logger 一致）：
      - span.session_id 非空 → {base_dir}/sessions/{sid}/traces.md
      - span.session_id 为空 → {base_dir}/_no_session/traces.md

    一条 trace（span 树）结构上隶属一次 run、进而隶属一个 session，故按 session
    分片与其他事件流对齐；per-file 锁使不同 session 的 span 写入互不阻塞。
    内存镜像 _spans 跨 session 保留，供 query_spans(run_id) 按 run 关联查询。
    """

    _HEADER = (
        "# Trace Spans\n\n"
        "> Auto-generated by Pandaren Agent SDK.\n\n"
        "| 时间 | 类型 | 名称 | 状态 | 结束原因 | 耗时(ms) | Step | Run | 属性 |\n"
        "|------|------|------|------|----------|----------|------|-----|------|\n"
    )

    def __init__(self, base_dir: str | Path) -> None:
        self._base_dir = Path(base_dir)
        self._base_dir.mkdir(parents=True, exist_ok=True)
        # per-file 锁：不同 session 的 traces 写入互不阻塞
        self._locks: dict[Path, threading.Lock] = {}
        self._locks_guard = threading.Lock()
        # 记忆已初始化过 header 的文件，避免每次写入都做磁盘检查
        self._headered: set[Path] = set()
        # 内存镜像：跨 session 保留，供 query_spans/get_spans 按 run 关联（历史行为）
        self._spans: list[Span] = []
        self._spans_guard = threading.Lock()

    def _resolve_path(self, span: Span) -> Path:
        sid = _sanitize_component(span.session_id)
        if sid:
            return self._base_dir / "sessions" / sid / "traces.md"
        return self._base_dir / "_no_session" / "traces.md"

    def _get_lock(self, path: Path) -> threading.Lock:
        lock = self._locks.get(path)
        if lock is not None:
            return lock
        with self._locks_guard:
            lock = self._locks.get(path)
            if lock is None:
                lock = threading.Lock()
                self._locks[path] = lock
            return lock

    def _ensure_header(self, path: Path) -> None:
        if path in self._headered:
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(self._HEADER, encoding="utf-8")
        self._headered.add(path)

    def export_span(self, span: Span) -> None:
        with self._spans_guard:
            self._spans.append(span)
        path = self._resolve_path(span)
        lock = self._get_lock(path)
        with lock:
            self._ensure_header(path)
            ts = span.end_time.strftime("%H:%M:%S") if span.end_time else ""
            span_type = _SPAN_TYPE_ICON.get(span.span_type.value, span.span_type.value)
            name = f"`{span.name}`"
            if span.status.value == "ok":
                status = "✅ ok"
            elif span.status.value == "cancelled":
                status = "⏸️ cancelled"
            else:
                status = "❌ error"
            duration = f"**{span.duration_ms:.0f}**" if span.duration_ms is not None else ""
            step = str(span.step_n) if span.step_n is not None else ""
            run_short = f"`{span.run_id[:8]}`" if span.run_id else ""
            terminal_reason = span.attributes.get("terminal_reason", "") if span.attributes else ""
            attrs = ""
            if span.attributes:
                # 白名单按固定顺序渲染，保证列可读、跨行对齐。
                # 注意：这里的键必须覆盖 span 上实际挂载的全部「可观测口径」，
                # 否则会出现「span 有数据但 traces.md 看不到」的口径不统一
                # （历史上 model / cached_tokens / cost_usd 就是因此漏渲染，
                #  逼得看板去解析 logs.md 自由文本，见 dashboard 需求设计 §4.2/§4.7）。
                _ORDERED_ATTR_KEYS = (
                    "model",                       # 每次调用实际模型（支持中途换模型）
                    "provider",                    # 平台名（dashscope/volcengine/openai/deepseek）；按 provider 分账/分组
                    "input_tokens", "output_tokens",
                    "cached_tokens",               # prefix cache 命中 token 数
                    "cache_creation_input_tokens", # 缓存写入 token 数（Anthropic 语义）
                    "cache_hit_ratio",             # 命中率 %
                    # 注：cost_usd / total_cost 已移除——SDK 只记 token/命中等事实，
                    # 费用由应用层从这些事实 + 价格表自算（看板 cost_breakdown）。
                    "tool_name", "tool_calls_count",
                    "duration_ms",
                )
                parts = [
                    f"`{k}`={span.attributes[k]}"
                    for k in _ORDERED_ATTR_KEYS
                    if k in span.attributes
                ]
                if parts:
                    attrs = ", ".join(parts)
            line = f"| {ts} | {span_type} | {name} | {status} | {terminal_reason} | {duration} | {step} | {run_short} | {attrs} |\n"
            with open(path, "a", encoding="utf-8") as f:
                f.write(line)

    def get_spans(self, run_id: str | None = None) -> list[Span]:
        with self._spans_guard:
            if run_id:
                return [s for s in self._spans if s.run_id == run_id]
            return list(self._spans)

    def query_spans(self, run_id: str) -> list[Span]:
        """TracerBackend Protocol 要求的查询接口。"""
        return self.get_spans(run_id)

    def clear(self) -> None:
        with self._spans_guard:
            self._spans.clear()

    def __repr__(self) -> str:
        return f"MarkdownTracerBackend(base_dir='{self._base_dir}', mode='sharded')"


class MarkdownMetricsBackend:
    """Markdown Metrics 后端：覆盖写入 metrics.md。"""

    def __init__(self, base_dir: str | Path) -> None:
        self._base_dir = Path(base_dir)
        self._base_dir.mkdir(parents=True, exist_ok=True)
        self._md_path = self._base_dir / "metrics.md"
        self._lock = threading.Lock()
        self._counters: dict[str, int] = defaultdict(int)
        self._histograms: dict[str, list[float]] = defaultdict(list)
        self._gauges: dict[str, float] = {}
        self._write_count = 0
        # 进程退出兜底刷盘：metrics 按批（每 10 次写）刷盘省 IO，退出时最后不足一批的
        # 写入会滞留内存 → 裸文件停在旧快照/硬杀丢尾。atexit 覆盖 Ctrl+C(SIGINT→正常
        # 退栈) 与正常退出；SIGKILL/无处理的 SIGTERM 不触发，但 run 边界刷盘已兜住
        # 「run 已结束」的场景，仅剩「run 执行中被强杀」这一可接受的丢失窗口。
        atexit.register(self.flush)

    @staticmethod
    def _make_key(name: str, labels: dict[str, str]) -> str:
        if not labels:
            return name
        label_str = ",".join(f"{k}={v}" for k, v in sorted(labels.items()))
        return f"{name}{{{label_str}}}"

    def record_counter(self, name: str, value: int, labels: dict[str, str]) -> None:
        key = self._make_key(name, labels)
        with self._lock:
            self._counters[key] += value
            self._write_count += 1
            if self._write_count % 10 == 0:
                self._flush_to_file()

    def record_histogram(self, name: str, value: float, labels: dict[str, str]) -> None:
        key = self._make_key(name, labels)
        with self._lock:
            self._histograms[key].append(value)
            self._write_count += 1
            if self._write_count % 10 == 0:
                self._flush_to_file()

    def record_gauge(self, name: str, value: float, labels: dict[str, str]) -> None:
        key = self._make_key(name, labels)
        with self._lock:
            self._gauges[key] = value
            self._write_count += 1
            if self._write_count % 10 == 0:
                self._flush_to_file()

    def _flush_to_file(self) -> None:
        lines = [
            "# Metrics Summary\n",
            f"> Last updated: {datetime.now(timezone.utc).isoformat()}\n", "",
        ]
        if self._counters:
            lines += ["## Counters\n", "| 指标 | 值 |", "|------|------|"]
            for name, value in sorted(self._counters.items()):
                lines.append(f"| {name} | {value} |")
            lines.append("")
        if self._histograms:
            lines += ["## Histograms\n", "| 指标 | count | avg | min | max | sum |",
                       "|------|-------|-----|-----|-----|-----|"]
            for name, values in sorted(self._histograms.items()):
                if values:
                    lines.append(
                        f"| {name} | {len(values)} | {sum(values)/len(values):.1f} "
                        f"| {min(values):.1f} | {max(values):.1f} | {sum(values):.1f} |"
                    )
            lines.append("")
        if self._gauges:
            lines += ["## Gauges\n", "| 指标 | 值 |", "|------|------|"]
            for name, value in sorted(self._gauges.items()):
                lines.append(f"| {name} | {value:.4f} |")
            lines.append("")
        self._md_path.write_text("\n".join(lines), encoding="utf-8")

    def flush(self) -> None:
        with self._lock:
            self._flush_to_file()

    def get_summary(self) -> dict[str, Any]:
        with self._lock:
            summary: dict[str, Any] = {
                "counters": dict(self._counters),
                "gauges": dict(self._gauges),
                "histograms": {},
            }
            for key, values in self._histograms.items():
                if values:
                    summary["histograms"][key] = {
                        "count": len(values), "min": min(values),
                        "max": max(values), "avg": sum(values) / len(values),
                        "sum": sum(values),
                    }
            self._flush_to_file()
            return summary

    def __repr__(self) -> str:
        return f"MarkdownMetricsBackend(path='{self._md_path}')"


class MarkdownLoggerBackend:
    """Markdown Logger 后端：按 session_id 分片写入。

    路径规则：
      - record.get('session_id') 非空 → {base_dir}/sessions/{sid}/logs.md
      - 否则                          → {base_dir}/_no_session/logs.md
    """

    _HEADER = (
        "# Agent Logs\n\n"
        "> Auto-generated by Pandaren Agent SDK.\n\n"
        "| 时间 | 级别 | 模块 | 消息 | Agent | Session | Run | Step | 详情 |\n"
        "|------|------|------|------|-------|---------|-----|------|------|\n"
    )

    def __init__(self, base_dir: str | Path) -> None:
        self._base_dir = Path(base_dir)
        self._base_dir.mkdir(parents=True, exist_ok=True)
        self._locks: dict[Path, threading.Lock] = {}
        self._locks_guard = threading.Lock()
        self._headered: set[Path] = set()

    def _resolve_path(self, record: dict) -> Path:
        sid = _sanitize_component(str(record.get("session_id", "") or ""))
        if sid:
            path = self._base_dir / "sessions" / sid / "logs.md"
        else:
            path = self._base_dir / "_no_session" / "logs.md"
        return path

    def _get_lock(self, path: Path) -> threading.Lock:
        lock = self._locks.get(path)
        if lock is not None:
            return lock
        with self._locks_guard:
            lock = self._locks.get(path)
            if lock is None:
                lock = threading.Lock()
                self._locks[path] = lock
            return lock

    def _ensure_header(self, path: Path) -> None:
        if path in self._headered:
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(self._HEADER, encoding="utf-8")
        self._headered.add(path)

    def write_log(self, record: dict) -> None:
        path = self._resolve_path(record)
        lock = self._get_lock(path)
        with lock:
            self._ensure_header(path)
            ts = record.get("timestamp", "")
            if isinstance(ts, datetime):
                ts = ts.strftime("%H:%M:%S")
            elif isinstance(ts, str) and len(ts) > 19:
                ts = ts[11:19]
            level = record.get("level", "INFO")
            level_badge = _LOG_LEVEL_BADGE.get(level, level)
            module = f"`{record.get('module', '')}`" if record.get("module") else ""
            message = record.get("message", "").replace("|", "\\|").replace("\n", " ")
            agent_id = record.get("agent_id", "")
            session_id = record.get("session_id", "")
            sess_short = f"`{session_id[:12]}`" if session_id else ""
            run_id = record.get("run_id", "")
            run_short = f"`{run_id[:8]}`" if run_id else ""
            step_n = record.get("step_n")
            step = str(step_n) if step_n is not None else ""
            # 注：log_id 不进排除列表——markdown 表无专属列，放 extra_str 以 JSON 形式
            # 保留（不丢关联键）；sqlite 后端则落 log_id 专属列（结构化查询场景）。
            extra = {k: v for k, v in record.items()
                     if k not in ("level", "timestamp", "module", "message",
                                  "run_id", "step_n", "agent_id",
                                  "session_id")}
            import json
            extra_str = json.dumps(extra, ensure_ascii=False, default=str) if extra else ""
            extra_str = extra_str.replace("|", "\\|")
            line = (
                f"| {ts} | {level_badge} | {module} | {message} | {agent_id} | "
                f"{sess_short} | {run_short} | {step} | {extra_str} |\n"
            )
            with open(path, "a", encoding="utf-8") as f:
                f.write(line)

    def __repr__(self) -> str:
        return f"MarkdownLoggerBackend(base_dir='{self._base_dir}', mode='sharded')"
